version: "3"

services:
  advert:
    image: nginx:stable-alpine
    container_name: advert
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
